name = Detroit Ledger basic
description = 2 cols, teensy header
preview = preview.png
template = gnl-basic

; Regions
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/gnl-basic/gnl-basic.css
